### ISSUE TITLE
MuseLSL2

### ISSUE THREAD

**Issue by DominiqueMakowski** [mne-tools/mne-lsl#132]
I've been working on [MuseBSL](https://github.com/DominiqueMakowski/MuseBSL), an update/modernization/lightening of [muse-lsl](https://github.com/alexandrebarachant/muse-lsl) (see #95).

My goal is to replace pylsl by BSL, but I think I'll need some reassurance on how to do that.
In particular, the pylsl functions used are [StreamInfo](https://github.com/DominiqueMakowski/MuseBSL/blob/1efb63f755d21a4131b803273eadc346b543f28e/MuseBSL/stream.py#L44-L51), [StreamOutlet](https://github.com/DominiqueMakowski/MuseBSL/blob/1efb63f755d21a4131b803273eadc346b543f28e/MuseBSL/stream.py#L60) and [local_clock()](https://github.com/DominiqueMakowski/MuseBSL/blob/1efb63f755d21a4131b803273eadc346b543f28e/MuseBSL/muse.py#L90).

Is it correct that replacing `pylsl.` by `bsl.lsl.` should do the job? Is there some other improvements that could be implemented to make full use of the BSL benefits? Thanks!

**Comment by DominiqueMakowski** [comment]
One thing to note, the `desc` object was a callable in pylsl, but now isn't, so one need to change:

```python
info = pylsl.StreamInfo(...)
info.desc().append_child_value()
```

to:

```python
info =  bsl.lsl.StreamInfo(...)
info.desc.append_child_value()
```

**Comment by mscheltienne** [comment]
Hello,

Yes, there are a couple of minor differences in the API, e.g. `desc` is now a property instead of a method.
The goal was to modernize and make the API more "python-like". 

That said, you can simplify the code to set the channel descriptions, e.g. https://github.com/DominiqueMakowski/MuseBSL/blob/c1ea0bc2f61816b3c884b92d534b96cfceb3641a/MuseBSL/stream.py#L32-L37

```
sinfo = StreamInfo(...)
sinfo.set_channel_names(["TP9", "AF7", "AF8", "TP10", "Right AUX"])
sinfo.set_channel_types(["eeg"] * 4 + ["misc"])
sinfo.set_channel_units("microvolts")
```

Same for other `StreamInfo`, and you'll need to pin to `main` or to `1.0` or above (almost done.. got a bit submerged in side-task this past week). Either look at the code directly, or at the `dev` documentation build: https://fcbg-hnp-meeg.github.io/bsl/dev/index.html It eliminates the need to interact with the `desc` XML element tree.

------------

Also, your `push` function seems wrong: https://github.com/DominiqueMakowski/MuseBSL/blob/91699ff4b15ec26a9ef3410a1f7a6f7a3247e20f/MuseBSL/stream.py#L100-L102

In LSL, a sample is an array of shape `(n_channels,)`. In the case of a `bsl.lsl.StreamOutlet.push_sample`, it's optimal to push a numpy array of the same dtype as the `StreamOutlet` (float 32 in your case I think) which is C-contiguous. It's also True to some extend in `pylsl`, although it usually works through python list instead of numpy arrays, and the difference is not that important for that operation anyway.
Your push function is called by the callback: https://github.com/DominiqueMakowski/MuseBSL/blob/91699ff4b15ec26a9ef3410a1f7a6f7a3247e20f/MuseBSL/muse.py#L259-L308

Which seems to fill an array `self.data` with the samples received from 44, 41, 38, 32, 35 (I assume, your 5 channels); and then when the last sample (35) is received, you call the EEG callback function which calls `push`. So now, in push, you are iterating on this data array of shape `(5,)` and trying to push channel by channel instead of the entire "sample" at once.

At least, that's how I read the code, I might be completely wrong. Do you have any other traceback with this `missing sample 1`? I've never seen it thrown by LSL yet :cry:

**Comment by DominiqueMakowski** [comment]
I managed to simplify the code a lot with the convenience methods to set channel names etc. Cheers for that. 
The only thing that we still set manually is the [manufacturer](https://github.com/DominiqueMakowski/MuseBSL/blob/main/MuseBSL/stream.py#L27), but I'm not sure it's super useful and standard (again, this was in muse-lsl, but I am happy to remove it if it's not of much use to make MuseBSL as light as possible).

> Also, your push function seems wrong:
I checked and you are probably right, it seems like we're pushing channel by channel (assuming the second axis is the channels).

Do you suggest to change it from:

```python
    def push(data, timestamps, outlet):
        for i in range(data.shape[1]):
            outlet.push_sample(data[:, i], timestamps[i])
```

to:

```python
    def push(data, timestamps, outlet):
        outlet.push_sample(data[:, :], timestamps[:])
```

As you say we can push the entire array?

**Comment by mscheltienne** [comment]
The manufacturer is less standardize than the already not that standardized channel names/types/units. 
You can leave it or remove it; honestly it doesn't add any useful information.

For the push operation, if `data` is of shape `(n_channels,)` then you should indeed do `outlet.push_sample(data, timestamp)` where `timestamp` is a float; and if you have several samples, i.e. a chunk of shape `(n_samples, n_channels)`, then you should do `outlet.push_chunk(data, timestamp)` where `timestamp` is again a `float`, the acquisition timestamp of the *last* sample (i.e. `data[-1, :]`).

From reading your code last time, it did look to me like `data` was of shape `(5,)`, i.e. `(n_channels,)`.

**Comment by mscheltienne** [comment]
@DominiqueMakowski Hello! Quick ping so you notice that the repository has moved and was renamed.
`bsl` will still be available on PyPI, up to the existing minor version and on the repository `https://github.com/fcbg-hnp-meeg/bsl`, and this repository `mne-lsl` will have a stable release on PyPI and `conda-forge` soon.

**Comment by DominiqueMakowski** [comment]
Thanks for the headsup :)

**Comment by DominiqueMakowski** [comment]
Just to clarify,

> then you should do outlet.push_chunk(data, timestamp) where timestamp is again a float, the acquisition timestamp of the last sample (i.e. data[-1, :])

This is an example of data for the eeg stream:

```
Timestamps:  [367030.56168572 367030.56538407 367030.56908243 367030.57278079
 367030.57647915 367030.58017751 367030.58387587 367030.58757423
 367030.59127259 367030.59497095 367030.59866931 367030.60236767]
-------------------------
Data:  [[ -616.2109375    964.84375      642.08984375  -854.98046875
  -1000.          -851.07421875   567.87109375   981.4453125
   -541.015625   -1000.         -1000.           152.83203125]
 [ -858.88671875   595.703125     864.2578125   -692.3828125
  -1000.         -1000.           161.1328125    999.51171875
   -354.00390625 -1000.         -1000.           -84.47265625]
 [ -802.734375    -197.265625     104.4921875   -578.125
   -831.54296875  -793.9453125   -353.02734375   106.4453125
   -399.90234375  -746.58203125  -799.31640625  -537.109375  ]
 [ -183.59375      997.55859375   999.51171875   233.3984375
  -1000.          -337.890625     957.51953125   999.51171875
    226.5625     -1000.          -511.23046875   869.140625  ]
 [    0.             0.             0.             0.
      0.             0.             0.             0.
      0.             0.             0.             0.        ]]
```

dimensions (12,) and (5, 12)

The timestamps are different. However, you suggest to just do

```python
    def push(data, timestamps, outlet):
        outlet.push_sample(data, timestamps[-1]) 
```
and store the last one is that correct?

**Comment by mscheltienne** [comment]
`(5, 12)` seems to be 5 channels and 12 samples.
If you have a single sample, array of shape `(12,)`: `outlet.push_sample(data, timestamp)`
If you have a chunk of samples, array of shape `(5, 12)`: `outlet.push_sample(data.T, timestamps[-1])` (note the transpose since LSL expects the chunk to be of shape (n_samples, n_channels)).

**Comment by mscheltienne** [comment]
It will always be one timestamp per sample, thus one timestamp for all channels. I think it should be fine.

**Comment by DominiqueMakowski** [comment]
pull_chunk seems to work! cheers :)

Moving forward, should I change the imports of `bsl` to `mne_lsl` ?

**Comment by mscheltienne** [comment]
I would suggest so since I archived `bsl` and the future release will be only on `mne_lsl`. For now, you'll have to pin to the main version in the `setup.py` (or `setup.cfg` or `pyproject.toml`) until I release the first version.

**Comment by DominiqueMakowski** [comment]
Alright, as far as I'm concerned, everything seems to work neatly, I updated the [README](https://github.com/DominiqueMakowski/MuseLSL2).

Let me know when you make a pypi release.

Again, thanks for your help and patience, much appreciated

Good luck with mne-lsl ;)

**Comment by mscheltienne** [comment]
First release done: https://pypi.org/project/mne-lsl/
Conda-forge in the coming days.
