### ISSUE TITLE
Should we support the FieldTrip buffer

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-lsl#138]
Hello @britta-wstnr! Eric has designated you as FieldTrip buffer-contact person, so here I am :)

This package, `mne-lsl` (for now, name can be changed), implements a Stream object which behaves mostly like a `Raw` and which interacts with a real-time LSL stream. At term, it should be compatible with MEGIN's system.
The Stream object has an abstraction layer which should allow us to (relatively) painlessly add another Stream format than LSL, say for instance, the FT buffer.

Question: Is the Fieldtrip buffer very used and would it be sensible to support, even if LSL is gaining in popularity (especially on the EEG market)?

**Comment by britta-wstnr** [comment]
Mh, good question. I don't think I would make it number 1 priority. FieldTrip might have actual numbers for how many people use it (at least a few years back they had knowledge about users per module if I'm not mistaken). I can go ask if that would help?

**Comment by mscheltienne** [comment]
Thanks, that would be very helpful if you could ask around :)

**Comment by britta-wstnr** [comment]
Okay so I asked around a bit and I came to the following conclusion: it probably is not super high-priority as people I asked seem to favor LSL or said that they do not know many people using it still.
So maybe a situation where we wait for a user to request it?

**Comment by mscheltienne** [comment]
Thanks for asking around :)

**Comment by britta-wstnr** [comment]
To record this here in case we do want to support the FieldTripBuffer at some point in the future - @robertoostenveld just shared some pointers and tips with me (thanks, Robert!):

The [eegsynth](https://github.com/eegsynth/eegsynth) package is a package for converting real-time EEG into sounds, music and visual effects. As such, it does streaming and realtime processing in Python (developed since ten years, and Robert is part of this). Of potential interest here is:
- there is a file [`FieldTrip.py`](https://github.com/eegsynth/eegsynth/blob/master/lib/FieldTrip.py)   which includes a test for server and client implementation
- there is also a way to bridge, using the eegsynth `lsl2ft` module
- Robert also flagged his contribution of https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylsl.py that allows compilation and packaging of `pylsl` in case we need it.
