### ISSUE TITLE
Stream events/annotations

### ISSUE THREAD

**Issue by vferat** [mne-tools/mne-lsl#199]
I would be nice to be able to stream events/annotations (if present) on a second outlet (`StreamOutlet` of type 'string, i.e. irregular) while playing back a file using `mne_lsl_player`.

Ultimately, it would be also nice to render these events in the viewer.

In our use case, this would allow us to play back EEG data as well as start events of every fMRI volume and work with online EEG-fMRI correction.

**Comment by mscheltienne** [comment]
`Annotation` have 3 properties: `description`, `onset` and `duration`. In other words, they have both an `onset` and `offset`. What would be the most convenient way to access those information on your end?

Thinking out loud:
- A separate StreamOutlet `Annotation`.
- Each unique annotation description would yield a separate channel, to separate different annotations and easily select which one is interesting at the client end.
- To easily select channel(s) of interest, an `mne_lsl.stream.StreamLSL` could be used if the `dtype` is numeric (also improves streaming performance compared to string based `dtypes`
- An irregular sampling-rate seems to make more sense in my opinion
- How to deal with overlapping annotations? It's an edge-case since overlapping annotations with the same description can only be created programmatically, but it needs to be covered.

Maybe a `dtype=np.int8` with an irregular sampling rate, streaming `+X` for the onsets and `-X` for the offsets, incrementing by 1 if we have overlapping annotations.

e.g.

```
# default without overlapping annotations
t= ...    +1
t= ...    -1
t= ...    +1
t= ...    -1

# with overlapping annotations
t= ...    +1
t= ...    -1
t= ...    +1
t= ...    +2
t= ...    -2
t= ...    +2
t= ...    -1
t= ...    -2
```

WDYT?

**Comment by mscheltienne** [comment]
Better idea, irregularly sampled stream of `dtype` float where each channel is a separate channel description, each emition timestamp is the onset and each value is the duration.
